Repository OCA/web-api, pull requests merged in 2024-07, with the labels that each got.

#46 [14.0][ADD] endpoint_jsonifier
  endpoint_jsonifier/README.rst
  endpoint_jsonifier/__init__.py
  endpoint_jsonifier/__manifest__.py
  endpoint_jsonifier/models/__init__.py
  endpoint_jsonifier/models/endpoint_mixin.py
  endpoint_jsonifier/readme/CONTRIBUTORS.rst
  endpoint_jsonifier/readme/DESCRIPTION.rst
  endpoint_jsonifier/readme/USAGE.rst
  endpoint_jsonifier/static/description/index.html
  endpoint_jsonifier/views/endpoint_endpoint.xml
  setup/endpoint_jsonifier/odoo/addons/endpoint_jsonifier
  setup/endpoint_jsonifier/setup.py
Labels: bot is merging ⏳

#37 [14.0][FIX] endpoint_route_handler: Use dedicated cursor for registry
  endpoint_route_handler/models/ir_http.py
Labels: bot is merging ⏳

#45 [16.0][IMP] endpoint: endpoint multi-company
  endpoint/__manifest__.py
  endpoint/models/endpoint_mixin.py
  endpoint/security/ir_rule.xml
  endpoint/static/description/index.html
  endpoint/views/endpoint_view.xml
Labels: bot is merging ⏳, ready to merge, approved

#49 [14.0][IMP] endpoint: add log function
  endpoint/models/endpoint_mixin.py
  endpoint/tests/test_endpoint.py
Labels: bot is merging ⏳

#51 [16.0] endpoint: add log function
  endpoint/models/endpoint_mixin.py
  endpoint/tests/test_endpoint.py
Labels: bot is merging ⏳, approved

#53 [IMP] endpoint_route_handler: add request_content_type application_js…
  endpoint_route_handler/models/endpoint_route_handler.py
Labels: bot is merging ⏳

#54 [14.0] Add endpoint_cache
  endpoint_cache/__init__.py
  endpoint_cache/__manifest__.py
  endpoint_cache/models/__init__.py
  endpoint_cache/models/endpoint_mixin.py
  endpoint_cache/readme/CONTRIBUTORS.rst
  endpoint_cache/readme/DESCRIPTION.rst
  endpoint_cache/readme/ROADMAP.rst
  endpoint_cache/readme/USAGE.rst
  endpoint_cache/tests/__init__.py
  endpoint_cache/tests/test_endpoint.py
  endpoint_cache/views/endpoint_view.xml
  setup/endpoint_cache/odoo/addons/endpoint_cache
  setup/endpoint_cache/setup.py
Labels: bot is merging ⏳

#56 [14.0] endpoint: add basic mixin view
  endpoint/views/endpoint_view.xml
  endpoint_auth_api_key/views/endpoint_view.xml
  endpoint_cache/views/endpoint_view.xml
  endpoint_jsonifier/views/endpoint_endpoint.xml
Labels: bot is merging ⏳

#57 [16.0][FWD] endpoint: add basic mixin view
  endpoint/views/endpoint_view.xml
  endpoint_auth_api_key/views/endpoint_view.xml
Labels: bot is merging ⏳
